apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: ClusterIP  # Changed from ClusterIP to LoadBalancer
  selector:
    role: frontend
